version: '3.7'
services:
  app-prod:
    container_name: rockfeller-frontend
    env_file: ./.env
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - '80:80'

networks:
  default:
    external:
      name: rockfeller-network